### PR TITLE
Add link to status page

### PR DESCRIPTION
**Pull request by etoews**

### CODE REVIEW

**Comment by ktbartholomew** [comment]
LGTM

**Comment by etoews** [comment]
@ktbartholomew I don't see the link on https://getcarina.com/ yet. Does something else need to happen?

**Comment by ktbartholomew** [comment]
Oh, I wasn't paying attention to which repo this was. The change is correct, but should have been made on https://github.com/rackerlabs/nexus-control. This repo will be used whenever I finally finish my big control repo overhaul.

**Comment by ktbartholomew** [comment]
https://github.com/rackerlabs/nexus-control/pull/347

**Comment by etoews** [comment]
repospora

**Pull request merged**
